CREATE TABLE "GCG_3998_DlyBalEmp"(
"BIRUNID" BIGINT,
"EMPL" CHAR(5),
"EMPLOYEE" CHAR(40),
"CHARGE_DATE" DATE,
"START_TIME" CHAR(4),
"DATE_OUT" DATE,
"END_TIME" CHAR(4),
"MACHINE" CHAR(4),
"JOB" CHAR(6),
"SUFFIX" CHAR(3),
"SEQ" CHAR(6),
"HOURS_WORKED" NUMERIC(12,4),
"FLAG_INDIRECT" CHAR(1),
"HOURS_ACTUAL" CHAR(10),
"DESCRIPTION" CHAR(31),
"ON_TIME" CHAR(10),
"OFF_TIME" CHAR(10));

 